spring:
  application:
    name: "review-service"
  cloud:
    kubernetes:
      config:
        namespace: bistroad-prod
swagger:
  doc:
    operation:
      review:
        get-review:
          description: Get a review by ID
        get-reviews:
          description: Search reviews
        post-review:
          description: Create a review
        patch-review:
          description: Update a review partially
        delete-review:
          description: Delete a review
    model:
      page:
        page:
          description: Page number
        size:
          description: Number of elements on a page
        sort:
          description: Sorting properties (e.g. sort=name,desc, sort=price,asc)